import Head from 'next/head'
import Link from 'next/link'
import { useQuery } from 'urql'
import { PRODUCT_QUERY } from '../lib/query'
import Product from '../components/Product'
import { Gallery } from '../styles/Gallery'

export default function Home() {
  // Fetch products from Strapi
  const [results] = useQuery({ query: PRODUCT_QUERY })
  //console.log(results)
  const { data, fetching, error } = results

  //Check for the data coming in
  if (fetching) return <p>Loading...</p>
  if (error) return <p>Oh no ...{error.message}</p>
  //console.log(data)

  const products = data.products.data
  console.log(products)

  return (
    <div>
      <Head>
        <title>Ecommerce </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>welcome next</h1>
        <Gallery>
          {products.map((product, index) => (
            <Product product={product} key={index} />
          ))}
        </Gallery>
      </main>
    </div>
  )
}
